version: "3.0"
services:
  react-dev:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=production